// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb0WKdE0pHBF72isO6xrViBEKw1uNg6eM',
    appId: '1:651223228136:web:d4d00282ac9a4eff03335d',
    messagingSenderId: '651223228136',
    projectId: 'todo-c10-mon',
    authDomain: 'todo-c10-mon.firebaseapp.com',
    storageBucket: 'todo-c10-mon.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJIPTKHHwUfk3kLlYFWTxag_tj2qkiPuE',
    appId: '1:651223228136:android:f6252250654cb30403335d',
    messagingSenderId: '651223228136',
    projectId: 'todo-c10-mon',
    storageBucket: 'todo-c10-mon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB75ZnOuzIfoebEiWyPuGx107KB3ywnCJg',
    appId: '1:651223228136:ios:0be6a878f542a7f003335d',
    messagingSenderId: '651223228136',
    projectId: 'todo-c10-mon',
    storageBucket: 'todo-c10-mon.appspot.com',
    iosBundleId: 'com.example.todoAppC10Mon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB75ZnOuzIfoebEiWyPuGx107KB3ywnCJg',
    appId: '1:651223228136:ios:7f300ebbe8d6aa3a03335d',
    messagingSenderId: '651223228136',
    projectId: 'todo-c10-mon',
    storageBucket: 'todo-c10-mon.appspot.com',
    iosBundleId: 'com.example.todoAppC10Mon.RunnerTests',
  );
}
